{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rtweet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rtweet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rtweet/rtweet_{{ version }}.tar.gz
  sha256: 82c4fd4ad02782396ba794431ca7cd567475d3cb1b19a2f733e0bd5a545081f0

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bit64 >=4.0.5
    - r-curl >=4.3.2
    - r-httr >=1.3.0
    - r-httr2 >=0.2.2
    - r-jsonlite >=0.9.22
    - r-lifecycle >=1.0.0
    - r-progress >=1.2.2
    - r-rlang >=0.4.10
    - r-tibble >=1.3.4
    - r-withr >=2.5.0
  run:
    - r-base
    - r-bit64 >=4.0.5
    - r-curl >=4.3.2
    - r-httr >=1.3.0
    - r-httr2 >=0.2.2
    - r-jsonlite >=0.9.22
    - r-lifecycle >=1.0.0
    - r-progress >=1.2.2
    - r-rlang >=0.4.10
    - r-tibble >=1.3.4
    - r-withr >=2.5.0

test:
  commands:
    - $R -e "library('rtweet')"           # [not win]
    - "\"%R%\" -e \"library('rtweet')\""  # [win]

about:
  home: https://docs.ropensci.org/rtweet/
  dev_url: https://github.com/ropensci/rtweet/
  doc_url: https://docs.ropensci.org/rtweet/reference/index.html
  license: MIT
  summary: "An implementation of calls designed to collect and organize Twitter data via Twitter's REST and stream Application Program Interfaces (API), which can be found at the following URL: <https://developer.twitter.com/en/docs>."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
