appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DVsIAdUik7cAMmydGoPp9XPKo/3+3qgXYpoMBaKR5OWu9p5CWN2ZQug/xwAISAUJD0mXpGTrIWFRxCWUPpk1RF0B5pL/panGldjepsG8HP+yznsDq4923akL5lmvlDuo8xZGUb2M4d2m11XC32Z1IGZzXhkyLh3BcIppfSfLyAJS7i3GOxPZL9Cotjz82B8eEL9nXyCwIND2L89QOeIyAQWrh1YYeXSk27/r8jHClqpwi8Amfju9lXtoV0I4yxS1Ntxzag/qAv+NmgZlZ7m3rso0FGJ8Z2nEYtHdLDOiycl10wLGMzkxyoNf86NBRrJxYtB6hDgdyvPSsszkJDC4+aDpSvkmlEMEkRcE5uvD4zmF3nHZNMN5GvACnZepSgjTS+KzwRQAAVN1EBIOZWpDPVN9SInhUEhgjwkVfvvR/UcTiQmfB1AXVIE4Js6KOXYEdiXLj3+IE0oUhZsAgDRv15Q58FiBcv9wDPtxfAB5w/jI3WYRMswsotVMVoySDI7J+fhwZ9tGTs6EGpp+hSehk1llSnSES6a2vBgBS/4zAqBc944tb+bxPSvPXz9jHlmODNlmE6lUzq4RyEev8ijsDHHpcMHo+okt+Wju0FLVIfOk5dNhSny6hXAjmKO1whITGk7yki4Ky7Ev51IFxpttRPvtwdWLPpjJWt2BQkqtIoU=}
bot:
  automerge: true
